[package]
name = "webl-lc-prep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-leet = "0.2.0"
rand = "0.8.5"
rstest = "0.19.0"
